name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          # install .codedoc dependencies
          (cd .codedoc && npm install)
          # install codedoc
          npm install @codedoc/cli
          # build repo
          (PATH=$(npm bin):$PATH && codedoc build)
          cp docs/assets/favicon.ico dist/docs/assets/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
